import prisma from '../src/lib/prisma'

const now = new Date()

function daysFromNow(n: number) {
  const d = new Date(now)
  d.setDate(d.getDate() + n)
  return d
}

const applications = [
  // Currently active guests (APPROVED, in Halle now)
  {
    guestName: 'Dr. Elena Rostova',
    guestEmail: 'elena.rostova@icea.uni-halle.de',
    dateOfBirth: new Date('1985-03-12'),
    homeAddress: 'ul. Tverskaya 15, 121002 Moskau, Russland',
    halleAddress: 'Adam-Kuckhoff-Strasse 17, 06108 Halle (Saale)',
    arrivalDate: daysFromNow(-20),
    departureDate: daysFromNow(40),
    photoUrl: '/uploads/mock-photo-1.jpg',
    hostName: 'Prof. Dr. Thomas Weber',
    status: 'APPROVED' as const,
    wlanAccess: true,
    libraryAccess: true,
    mensaPayments: true,
    vpnAccess: false,
    databaseAccess: true,
    cardActive: true,
    guestNumber: 'G-0001',
    applicationNumber: 'A-0001',
    wlanProvisioned: true,
    libraryProvisioned: true,
    provisionedAt: daysFromNow(-18),
    guestSignedAt: daysFromNow(-25),
    hostSignedAt: daysFromNow(-22),
    hostSignature: 'Prof. Dr. Thomas Weber',
  },
  {
    guestName: 'Prof. Anna Kowalski',
    guestEmail: 'anna.kowalski@uw.edu.pl',
    dateOfBirth: new Date('1972-06-20'),
    homeAddress: 'ul. Nowy Swiat 5, 00-001 Warschau, Polen',
    halleAddress: 'Heinrich-und-Thomas-Mann-Strasse 22, 06108 Halle (Saale)',
    arrivalDate: daysFromNow(-10),
    departureDate: daysFromNow(60),
    photoUrl: '/uploads/mock-photo-3.jpg',
    hostName: 'Prof. Dr. Sabine Muller',
    status: 'APPROVED' as const,
    wlanAccess: true,
    libraryAccess: true,
    mensaPayments: true,
    vpnAccess: false,
    databaseAccess: true,
    cardActive: true,
    guestNumber: 'G-0002',
    applicationNumber: 'A-0002',
    wlanProvisioned: true,
    libraryProvisioned: false,
    provisionedAt: daysFromNow(-8),
    guestSignedAt: daysFromNow(-15),
    hostSignedAt: daysFromNow(-12),
    hostSignature: 'Prof. Dr. Sabine Muller',
  },

  // Upcoming arrivals (APPROVED, not yet arrived)
  {
    guestName: 'Dr. Wei Zhang',
    guestEmail: 'wei.zhang@pku.edu.cn',
    dateOfBirth: new Date('1988-11-02'),
    homeAddress: 'No. 5 Yiheyuan Road, Haidian District, Peking, China',
    halleAddress: 'Georg-Forster-Strasse 2, 06108 Halle (Saale)',
    arrivalDate: daysFromNow(14),
    departureDate: daysFromNow(90),
    photoUrl: '/uploads/mock-photo-8.jpg',
    hostName: 'Prof. Dr. Klaus Richter',
    status: 'APPROVED' as const,
    wlanAccess: true,
    libraryAccess: true,
    mensaPayments: true,
    vpnAccess: false,
    databaseAccess: false,
    cardActive: true,
    guestNumber: 'G-0005',
    applicationNumber: 'A-0008',
    wlanProvisioned: false,
    libraryProvisioned: false,
    guestSignedAt: daysFromNow(-5),
    hostSignedAt: daysFromNow(-3),
    hostSignature: 'Prof. Dr. Klaus Richter',
  },
  {
    guestName: 'Dr. Amara Okafor',
    guestEmail: 'a.okafor@unilag.edu.ng',
    dateOfBirth: new Date('1990-07-18'),
    homeAddress: 'University Road, Akoka, Lagos, Nigeria',
    halleAddress: 'Ludwig-Wucherer-Strasse 8, 06108 Halle (Saale)',
    arrivalDate: daysFromNow(30),
    departureDate: daysFromNow(120),
    photoUrl: '/uploads/mock-photo-9.jpg',
    hostName: 'Prof. Dr. Thomas Weber',
    status: 'APPROVED' as const,
    wlanAccess: true,
    libraryAccess: false,
    mensaPayments: true,
    vpnAccess: false,
    databaseAccess: false,
    cardActive: true,
    guestNumber: 'G-0006',
    applicationNumber: 'A-0009',
    wlanProvisioned: false,
    libraryProvisioned: false,
    guestSignedAt: daysFromNow(-7),
    hostSignedAt: daysFromNow(-4),
    hostSignature: 'Prof. Dr. Thomas Weber',
  },

  // Pending host approval (guest has submitted)
  {
    guestName: 'Dr. Sara Beltran',
    guestEmail: 'sara.beltran@ub.edu',
    dateOfBirth: new Date('1991-01-30'),
    homeAddress: 'Carrer de la Universitat 12, 08007 Barcelona, Spanien',
    halleAddress: 'Ludwig-Wucherer-Strasse 8, 06108 Halle (Saale)',
    arrivalDate: daysFromNow(45),
    departureDate: daysFromNow(150),
    photoUrl: '/uploads/mock-photo-5.jpg',
    hostName: 'Prof. Dr. Thomas Weber',
    status: 'PENDING_HOST' as const,
    wlanAccess: true,
    libraryAccess: true,
    mensaPayments: true,
    vpnAccess: false,
    databaseAccess: false,
    cardActive: true,
    applicationNumber: 'A-0005',
    guestSignedAt: daysFromNow(-1),
  },
  {
    guestName: 'Dr. Yuki Tanaka',
    guestEmail: 'yuki.tanaka@tokyo.ac.jp',
    dateOfBirth: new Date('1987-07-22'),
    homeAddress: '7-3-1 Hongo, Bunkyo, Tokio 113-8654, Japan',
    halleAddress: 'Grosse Steinstrasse 73, 06108 Halle (Saale)',
    arrivalDate: daysFromNow(60),
    departureDate: daysFromNow(210),
    photoUrl: '/uploads/mock-photo-6.jpg',
    hostName: 'Dr. Anna Fischer',
    status: 'PENDING_HOST' as const,
    wlanAccess: true,
    libraryAccess: true,
    mensaPayments: true,
    vpnAccess: false,
    databaseAccess: true,
    cardActive: true,
    applicationNumber: 'A-0006',
    guestSignedAt: daysFromNow(-2),
  },

  // INVITED (host sent invite, guest hasn't completed)
  {
    guestName: '',
    guestEmail: 'lucia.martinez@uam.es',
    dateOfBirth: new Date('1993-04-10'),
    homeAddress: '',
    halleAddress: '',
    arrivalDate: daysFromNow(20),
    departureDate: daysFromNow(80),
    photoUrl: '',
    hostName: 'Prof. Dr. Sabine Muller',
    status: 'INVITED' as const,
    wlanAccess: false,
    libraryAccess: false,
    mensaPayments: true,
    vpnAccess: false,
    databaseAccess: false,
    cardActive: true,
    applicationNumber: 'A-0010',
    invitedBy: 'Prof. Dr. Sabine Muller',
  },
  {
    guestName: '',
    guestEmail: 'raj.patel@iitb.ac.in',
    dateOfBirth: new Date('1986-09-05'),
    homeAddress: '',
    halleAddress: '',
    arrivalDate: daysFromNow(35),
    departureDate: daysFromNow(100),
    photoUrl: '',
    hostName: 'Dr. Anna Fischer',
    status: 'INVITED' as const,
    wlanAccess: false,
    libraryAccess: false,
    mensaPayments: true,
    vpnAccess: false,
    databaseAccess: false,
    cardActive: true,
    applicationNumber: 'A-0011',
    invitedBy: 'Dr. Anna Fischer',
  },

  // EXPIRED
  {
    guestName: 'Dr. James Chen',
    guestEmail: 'james.chen@oxford.ac.uk',
    dateOfBirth: new Date('1989-09-14'),
    homeAddress: '10 Broad Street, Oxford OX1 3BJ, UK',
    halleAddress: 'Emil-Abderhalden-Strasse 25, 06108 Halle (Saale)',
    arrivalDate: daysFromNow(-90),
    departureDate: daysFromNow(-60),
    photoUrl: '/uploads/mock-photo-4.jpg',
    hostName: 'Dr. Anna Fischer',
    status: 'EXPIRED' as const,
    wlanAccess: true,
    libraryAccess: true,
    mensaPayments: true,
    vpnAccess: false,
    databaseAccess: false,
    cardActive: false,
    guestNumber: 'G-0003',
    applicationNumber: 'A-0004',
    wlanProvisioned: true,
    libraryProvisioned: true,
    provisionedAt: daysFromNow(-88),
    guestSignedAt: daysFromNow(-95),
    hostSignedAt: daysFromNow(-92),
    hostSignature: 'Dr. Anna Fischer',
  },

  // DEACTIVATED
  {
    guestName: 'Dr. Maria Schmidt',
    guestEmail: 'maria.schmidt@uni-halle.de',
    dateOfBirth: new Date('1980-04-15'),
    homeAddress: 'Bahnhofstrasse 20, 04107 Leipzig',
    halleAddress: 'Hansering 15, 06108 Halle (Saale)',
    arrivalDate: daysFromNow(-60),
    departureDate: daysFromNow(30),
    photoUrl: '/uploads/mock-photo-7.jpg',
    hostName: 'Prof. Dr. Klaus Richter',
    status: 'DEACTIVATED' as const,
    wlanAccess: false,
    libraryAccess: false,
    mensaPayments: false,
    vpnAccess: false,
    databaseAccess: false,
    cardActive: false,
    guestNumber: 'G-0004',
    applicationNumber: 'A-0007',
    wlanProvisioned: true,
    libraryProvisioned: true,
    provisionedAt: daysFromNow(-58),
    guestSignedAt: daysFromNow(-65),
    hostSignedAt: daysFromNow(-62),
    hostSignature: 'Prof. Dr. Klaus Richter',
  },

  // REJECTED
  {
    guestName: 'Dr. Piotr Nowak',
    guestEmail: 'p.nowak@uw.edu.pl',
    dateOfBirth: new Date('1975-12-01'),
    homeAddress: 'ul. Krakowskie Przedmiescie 26/28, Warschau, Polen',
    halleAddress: 'Universitatsplatz 10, 06108 Halle (Saale)',
    arrivalDate: daysFromNow(-30),
    departureDate: daysFromNow(30),
    photoUrl: '/uploads/mock-photo-10.jpg',
    hostName: 'Prof. Dr. Thomas Weber',
    status: 'REJECTED' as const,
    wlanAccess: false,
    libraryAccess: false,
    mensaPayments: false,
    vpnAccess: false,
    databaseAccess: false,
    cardActive: false,
    applicationNumber: 'A-0012',
    guestSignedAt: daysFromNow(-35),
  },

  // Host who has not done their part yet (PENDING_HOST without guest signature yet - legacy flow)
  {
    guestName: 'Dr. Markus Lehmann',
    guestEmail: 'markus.lehmann@uni-halle.de',
    dateOfBirth: new Date('1978-11-05'),
    homeAddress: 'Musterstrasse 42, 12345 Berlin',
    halleAddress: 'Universitatsplatz 10, 06108 Halle (Saale)',
    arrivalDate: daysFromNow(5),
    departureDate: daysFromNow(70),
    photoUrl: '/uploads/mock-photo-2.jpg',
    hostName: 'Prof. Dr. Thomas Weber',
    status: 'PENDING_HOST' as const,
    wlanAccess: true,
    libraryAccess: false,
    mensaPayments: true,
    vpnAccess: false,
    databaseAccess: false,
    cardActive: true,
    applicationNumber: 'A-0003',
    guestSignedAt: daysFromNow(-4),
  },
]

async function main() {
  console.log('Seeding database with fake data...')
  for (const app of applications) {
    await prisma.guestApplication.create({ data: app })
  }
  console.log(`Seeded ${applications.length} guest applications.`)

  const counts = await Promise.all([
    prisma.guestApplication.count(),
    prisma.guestApplication.count({ where: { status: 'APPROVED' } }),
    prisma.guestApplication.count({ where: { status: 'PENDING_HOST' } }),
    prisma.guestApplication.count({ where: { status: 'INVITED' } }),
    prisma.guestApplication.count({ where: { status: 'EXPIRED' } }),
    prisma.guestApplication.count({ where: { status: 'DEACTIVATED' } }),
    prisma.guestApplication.count({ where: { status: 'REJECTED' } }),
  ])
  console.log('Summary:', {
    total: counts[0],
    active: counts[1],
    pending: counts[2],
    invited: counts[3],
    expired: counts[4],
    deactivated: counts[5],
    rejected: counts[6],
  })
}

main()
  .catch((e) => {
    console.error('Seed failed:', e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
